version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: amitambaliya/24response-backend
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=24response-mysql-app
      - MYSQL_USER=24response
      - MYSQL_PASS=24response123
      - MYSQL_DB=24response
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "6000:6000"
    container_name: 24response
    restart: on-failure
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=24response123
      - MYSQL_USER=24response
      - MYSQL_PASSWORD=24response123 
      - MYSQL_DATABASE=24response
    container_name: 24response-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=24response-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: 24response-phpmyadmin-app
networks:
  frontend:
  backend: